[package]
name = "category_theory_for_programmers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "challenge1"
path = "challenge1.rs"
doctest = true
doc = true
